apiVersion: apps/v1
kind: Deployment
metadata:
  name: stationfront-deploy
  namespace: default
spec:
  # A deployment's specification really only 
  # has a few useful options
  
  # 1. How many copies of each pod do we want?
  replicas: 2

  # 2. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      app:  stationfront
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: stationfront
    spec:
      volumes:
      - name: logstationfrontnginx 
        hostPath:
         path: {{MY_LOGS}}/stationnginxfront
         type: Directory
      - name: logstationfronttomcat
        hostPath:
         path: {{MY_LOGS}}/stationtomcatfront
         type: Directory
      - name: angularconfiguration
        hostPath:
         path: {{ANGULAR_CONFIG}}
         type: Directory
      containers:
        - name: stationfront-nginx
          image: {{REPO_NEXUS_URL}}kagzouli/station-front-nginx:{{VERSION}}
          volumeMounts:
          - name: logstationfrontnginx  
            mountPath: /var/log/nginx/
          - name: angularconfiguration
            mountPath: /usr/share/nginx/html/assets/config
          ports:
          - containerPort: 80
            protocol: TCP
        - name: stationfront-tomcat
          image: {{REPO_NEXUS_URL}}kagzouli/station-front-tomcat:{{VERSION}}
          volumeMounts:
          - name: logstationfronttomcat 
            mountPath: /usr/local/tomcat/logs
          - name: angularconfiguration
            mountPath: /usr/local/tomcat/webapps/station-angular4-poc/assets/config
          ports:
          - containerPort: 8080
            protocol: TCP
