pip install  .

# Params
NB_USERS=15
WAIT_TIME=12
NAMESPACE_NAME="stationdev"
CONTAINER_NAME="stationback"
LOAD_TEST="D:\Karim\dev\workspace\StationDemoProject\loadTest\python3\loadtest\utils\k6\data.txt"
TOKEN=eyJraWQiOiJ5TUpJQ19JU3pVYzZCUzlxRzk4b2p5elBjTmZtNS10eFpUN3J6Ml9rN2VJIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULndvVUdXUmFfckdTUnBhcHI0OFFfRjJVcUY1VXhUMDFFMWdQQmNVRlhvT0UiLCJpc3MiOiJodHRwczovL2Rldi04ODQyNTQub2t0YXByZXZpZXcuY29tL29hdXRoMi9kZWZhdWx0IiwiYXVkIjoiYXBpOi8vZGVmYXVsdCIsImlhdCI6MTY5NzgxMjA1NiwiZXhwIjoxNjk3ODE1NjU2LCJjaWQiOiIwb2FlZzN5Z2hhTDltUWFsejBoNyIsInVpZCI6IjAwdWVnYzA2b3pnajEya2xlMGg3Iiwic2NwIjpbInByb2ZpbGUiLCJlbWFpbCIsIm9wZW5pZCJdLCJhdXRoX3RpbWUiOjE2OTc4MTIwNTYsInN1YiI6ImthcmltQGV4YWthLmNvbSIsImdyb3VwcyI6WyJtYW5hZ2VyIl0sImxvY2FsZSI6ImZyX0ZSIn0.Qb7eyEtiG5a5iSufThn44A5em6IRqiFuqO9wqmLUDiByRWapZ6mTEj1JUnwjdnieISV5XFn2umFtrwXmg_qkBGgQBS3f-f-Jc8X7_0SzJ9_lNJaAoOr1JYqVpnmQW9_U1fp9rPxswCF2sIQUdYXXjX6c5XZryl9L51_LuC4jdntNtYV4cQxpyjokZHsRf18Hgq_OUAGhF_qdUjxkInwNLiaEYX3XZGJpqFJdi_mvzuyYKlI0v-I_QexShZ4UN6d7jT-lnCm_43qT-srOhkSU1zUDqexK1NNcO8RekYQal9pFtsl3mo7AktT-na6K9TC9_JHX-KwKOB_ykt7kMLTzSg

# Exec
loadtest http://stationback.exakaconsulting.org/StationDemoSecureWeb/station/stations --nbr-users=${NB_USERS} --wait-time=${WAIT_TIME} --namespace-name=${NAMESPACE_NAME} --container-name=${CONTAINER_NAME} --token={TOKEN} --load-file=${LOAD_TEST}