pip install  .

# Params
NB_USERS=40
WAIT_TIME=6
NAMESPACE_NAME="stationdev"
CONTAINER_NAME="stationback"
LOAD_TEST="D:\Karim\dev\workspace\StationDemoProject\loadTest\python3\loadtest\utils\k6\data.txt"
TOKEN=eyJraWQiOiJ5TUpJQ19JU3pVYzZCUzlxRzk4b2p5elBjTmZtNS10eFpUN3J6Ml9rN2VJIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULnJpelU1anlseXpFd09QU21nVlBCbWtad21yRkFUWjFldDVLYUVGSndFZDAiLCJpc3MiOiJodHRwczovL2Rldi04ODQyNTQub2t0YXByZXZpZXcuY29tL29hdXRoMi9kZWZhdWx0IiwiYXVkIjoiYXBpOi8vZGVmYXVsdCIsImlhdCI6MTY5NzgxNzE3MCwiZXhwIjoxNjk3ODIwNzcwLCJjaWQiOiIwb2FlZzN5Z2hhTDltUWFsejBoNyIsInVpZCI6IjAwdWVnYzA2b3pnajEya2xlMGg3Iiwic2NwIjpbImVtYWlsIiwib3BlbmlkIiwicHJvZmlsZSJdLCJhdXRoX3RpbWUiOjE2OTc4MTIwNTYsInN1YiI6ImthcmltQGV4YWthLmNvbSIsImdyb3VwcyI6WyJtYW5hZ2VyIl0sImxvY2FsZSI6ImZyX0ZSIn0.Wy4Aip0Kke27eOUOLLlBTxh1klVeG6dcOaBONldqWlG0Psm9JFzGAv-CLJK4OovmXP_aZosDRoOkmroHPHCOIgfuPfbM-TOxCMO82Vc6CF1JLaB1WMi7oBPJWeQ8egptVC1YXdt4mwTdGSkEE5Yx5JskIpL1h6Tb3pgBo7TeNbI40grBTfKI52qAv7PvaVRQytU35-ZWluxNVV-cDdA1Whujo7vfWbmgOEds_yUqu2utSW5Qi533uNR8ExL9q4wSotkS2WKkGPUWrJjFuTTr02ZczqT4kEB8yqak92Esg60RiIcyvpp_3EfV0S5FP-Ti4LhgEfTRbOsfuwji_xdCLQ
# Exec
loadtest http://stationback.exakaconsulting.org/StationDemoSecureWeb/station/stations --nbr-users=${NB_USERS} --wait-time=${WAIT_TIME} --namespace-name=${NAMESPACE_NAME} --container-name=${CONTAINER_NAME} --token=${TOKEN} --load-file=${LOAD_TEST}