apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datastationdb
  namespace: {{ .Release.Namespace | quote }} 
spec:
  storageClassName: manual
  accessModes: 
    -  ReadWriteOnce
  resources:
    requests: 
      storage: 150Mi
