apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentvolume
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: {{ .Values.stationdb.storage.storageClass | quote}} 
  capacity:
    storage: {{ .Values.stationdb.storage.globalCapacity | quote}} 
  accessModes: 
    -  ReadWriteOnce
  hostPath:
    path: {{ .Values.stationdb.databaseData | quote  }} 
