{{- if (eq .Values.stationfront.ingress.type "TargetGroupBinding")   }}
apiVersion: elbv2.k8s.aws/v1beta1 
kind: TargetGroupBinding
metadata:
  name: station-front-tgb
  namespace: {{ .Release.Namespace | quote }}
  
spec:
  serviceRef:
    name: stationfrontservice 
    port: {{ .Values.stationfront.service.internalPort }} 
  targetGroupARN: {{ .Values.stationfront.ingress.targetGroupARN }}
  networking:
    ingress:
      - from:
        - ipBlock:
            cidr: 12.0.0.0/21
        ports:
        - port: {{ .Values.stationfront.service.internalPort }} 
          protocol: TCP
{{- end }}
