{{- if (ne .Values.stationdb.mode "externaldb")   }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stationdb-data 
  namespace: {{ .Release.Namespace | quote }} 
spec:
  storageClassName: {{ .Values.stationdb.storage.storageClass | quote}} 
  accessModes: 
    -  ReadWriteOnce
  resources:
    requests: 
      storage: {{ .Values.stationdb.storage.dataCapacity | quote}}
{{- end }}
