apiVersion: v1
kind: Secret
metadata:
  name: stationdb-secret 
  namespace:  {{ .Release.Namespace | quote }}
type: Opaque
data:
  database-password: {{ .Values.stationdb.mysqlPassword | b64enc | quote }}
