{{- if (ne .Values.stationdb.mode "internaldb")   }}
apiVersion: v1
kind: Secret
metadata:
  name: stationdb-secret 
  namespace:  {{ .Release.Namespace | quote }}
type: Opaque
data:
  # Database password
  database-password: {{ .Values.stationdb.mysqlPassword | b64enc | quote }}
  
  # Root database password
  database-rootpassword: {{ .Values.stationdb.mysqlRootPassword | b64enc |quote  }}

{{- end }} 
