apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  description: Applications
  sourceRepos:
    - "*"
  destinations:
    - server: "https://kubernetes.default.svc"
      namespace: "stationdev"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"