apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: station
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    exakaconsulting/strategy: "refresh"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: stationdev
  project: applications
  sources:
  - path: kubernetesaws/helm/station
    repoURL: 'https://github.com/kagzouli/StationDemoProject.git'
    targetRevision: main
    helm:
      releaseName: station
      valueFiles:
        - "values.yaml"
  syncPolicy:
    prune: true
    syncOptions:
    - CreateNamespace=true
