apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cadvisor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: shared
  source:
    chart: cadvisor
    helm:
      releaseName: cadvisor
    repoURL: https://ckotzbauer.github.io/helm-charts
    targetRevision: 2.2.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true