apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  project: shared
  source:
    chart: vault
    helm:
      releaseName: vault
      parameters: 
        - name: csi.agent.enabled
          value: "false"
        - name: server.dev.enabled
          value: "true" 
        - name: server.dev.devRootToken
          value: {{ .Values.vault.devRootToken | quote }}
        - name: ui.enabled
          value: "true"  

    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.25.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true