apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: exaka-runner-deployment
  namespace: cicd
spec:
  replicas: 2
  template:
    spec:
      repository: kagzouli/StationDemoProject
      labels:
        - station
        - deploy