apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: exaka-runner-build
  namespace: cicd
spec:
  replicas: 1
  template:
    spec:
      repository: kagzouli/StationDemoProject
      labels:
        - station
        - build