apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: exaka-runner-deployment
  namespace: cicd
spec:
  template:
    spec:
      repository: kagzouli/StationDemoProject