pipeline {
   agent { label 'stationslave' }
   
   tools { 
        maven 'Maven 3.3.9' 
        jdk 'jdk8' 
    }
   
    stages {
		
        stage ("stopBack") {
            steps {
		sh "kubectl delete service stationbackservice"
                sh "kubectl delete deploy stationback-deploy" 
            }
        }

        stage ("stopFront") {
            steps {
		sh "kubectl delete service stationfrontservice"
                sh "kubectl delete deploy stationfront-deploy" 
            }
        }
     }

     post { 
	always { 
		cleanWs()
	}
     }
}
