apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    app.kubernetes.io/name: fluentbit
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File  parsers.conf
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log 
        Parser            docker
        Mem_Buf_Limit     400MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    [OUTPUT]
        Name cloudwatch 
        Match   *stationdb*
        region {{ .Values.app.region }} 
        log_group_name stationdb-eks-log-group
        log_stream_prefix from-fluent-bit-
        log_key log
        auto_create_group false

    [OUTPUT]
        Name cloudwatch 
        Match   *stationredis*
        region {{ .Values.app.region }} 
        log_group_name stationredis-eks-log-group
        log_stream_prefix from-fluent-bit-
        log_key log
        auto_create_group false

    [OUTPUT]
        Name cloudwatch 
        Match   *stationback*
        region {{ .Values.app.region }} 
        log_group_name stationback-eks-log-group
        log_stream_prefix from-fluent-bit-
        log_key log
        auto_create_group false
    
    [OUTPUT]
        Name cloudwatch 
        Match   *stationfront*
        region {{ .Values.app.region }} 
        log_group_name stationfront-eks-log-group
        log_stream_prefix from-fluent-bit-
        log_key log
        auto_create_group false

  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   Off
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   json    log

