apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentvolume
  namespace: {{ .Release.Namespace | quote }}
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes: 
    -  ReadWriteOnce
  hostPath:
    path: {{ .Values.stationdb.databaseData | quote  }} 
