apiVersion: apps/v1
kind: Deployment
metadata:
  name: stationfront-deploy
  namespace: {{ .Release.Namespace | quote }}
spec:
  # A deployment's specification really only 
  # has a few useful options
  
  # 1. How many copies of each pod do we want?
  replicas: {{ .Values.stationfront.nbReplicas }}

  # 2. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      app:  stationfront
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: stationfront
    spec:
      containers:
        - name: stationfront-nginx
          image: {{ include "stationfront.image.label" . | quote }} 
          imagePullPolicy: {{ .Values.stationfront.image.pullPolicy | quote }}
          env:
          - name: AWS_REGION
            value: {{ .Values.stationfront.region | quote  }}
          - name: CLIENT_ID_TRAF_STAT
            value: {{ .Values.stationfront.clientIdTrafStat | quote  }}
          - name: OKTA_URL
            value: {{ .Values.stationfront.oktaUrl | quote  }}
          - name: CONTEXT_BACK_URL
            value: {{ include "stationback.contextpath" . | quote }} 
          ports:
          - containerPort: 80
            protocol: TCP
