apiVersion: v1
kind: Service
metadata:
  name: stationbackservice 
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.stationback.service.serviceType | quote }}
  ports:
  - port: {{ .Values.stationback.service.externalPort }}
    name: stationback
    {{- if or (eq .Values.stationback.service.serviceType "NodePort") (eq .Values.stationback.service.serviceType "LoadBalancer")  }}
    nodePort: {{ .Values.stationback.service.nodePort }}
     {{- end }}
    targetPort: 8080 
    protocol: TCP
  selector:
    app: stationback
