apiVersion: v1
kind: Service
metadata:
  name: stationdbservice 
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
  - port: 3306
    name: stationdb
    targetPort: 3306 
    protocol: TCP
  selector:
    app: stationdb
