- name: Message deploiement redis server
  debug:
    msg: "Deploiement redis server environnement {{environnement}}"

- name: Ensure Redis is present
  apt: pkg=redis-server state=latest

- name: Ensure Redis is started
  service: name=redis-server state=started enabled=yes

- name: Ensure Redis Configuration
  template: src="{{directory_saslivraison}}/redis.conf.j2" dest=/etc/redis/redis.conf owner=root group=root mode=0644
  notify: Redis Restart
