pipeline {
   agent { label 'stationslave' }
   
   tools { 
        maven 'Maven 3.3.9' 
        jdk 'jdk8' 
    }
   
    stages {
		
        stage ("PullFromRegistry") {
            steps {
                sh "docker pull ${REPO_NEXUS_URL}kagzouli/station-db:${VERSION}"
                sh "docker pull ${REPO_NEXUS_URL}kagzouli/station-back:${VERSION}"
                sh "docker pull ${REPO_NEXUS_URL}kagzouli/station-front-nginx:${VERSION}"
                sh "docker pull ${REPO_NEXUS_URL}kagzouli/station-front-tomcat:${VERSION}"
            }
        }


        stage ("WriteEnvFile") {
            steps {
                sh "echo MY_LOGS=${MY_LOGS} >> .env"
                sh "echo DATABASE_DATA=${DATABASE_DATA} >> .env"
                sh "echo VERSION=${VERSION} >> .env"
                sh "cat .env" 
            }
        }

        stage ("LaunchDockerCompose") {
            steps {
                sh "jenkins/deployWithDockerCompose/docker-compose up -d"
            }
        }

     }

     post { 
	always { 
		cleanWs()
	}
     }
}
