FROM tomcat:latest

MAINTAINER Karim GZ "kagzouli@exaka.com"

COPY lib/mysql-connector-java-8.0.15.jar /usr/local/tomcat/lib/mysql-connector-java-8.0.15.jar
COPY conf/context.xml /usr/local/tomcat/conf/context.xml
