apiVersion: v1
kind: Service
metadata:
  name: stationfrontpod 
  labels:
    run: stationfrontpod
spec:
  ports:
  - port: 14000
    targetPort: 8080
    protocol: TCP
  selector:
    run: stationfrontpod
  type: LoadBalancer
