apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: global-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      role: arn:aws:iam::{{ .Values.app.accountidentifier }}:role/station-secret-iam-role
      region: {{ .Values.app.region | quote  }} 