pipeline {
   agent { label 'stationslave' }
   
   tools { 
        maven 'Maven 3.3.9' 
        jdk 'jdk8' 
    }
   
    stages {
		
        stage ("startBack") {
            steps {
				sh "sed -i 's/{{VERSION}}/${VERSION}/g' kubernates/back/backDeployTemplate.yaml" 
				sh "sed -i 's+{{REPO_NEXUS_URL}}+${REPO_NEXUS_URL}+g' kubernates/back/backDeployTemplate.yaml"
				sh "sed -i 's+{{MY_LOGS}}+${MY_LOGS}+g' kubernates/back/backDeployTemplate.yaml"
				sh "sed -i 's+{{DATABASE_DATA}}+${DATABASE_DATA}+g' kubernates/back/backDeployTemplate.yaml"
				sh "cat kubernates/back/backDeployTemplate.yaml"
				sh "kubectl apply -f kubernates/back/backDeployTemplate.yaml"
                
				sh "sed -i 's+{{SERVICE_EXTERNAL_IP}}+${SERVICE_EXTERNAL_IP}+g' kubernates/back/backServiceTemplate.yaml"
				sh "cat kubernates/back/backServiceTemplate.yaml"
				sh "kubectl apply -f kubernates/back/backServiceTemplate.yaml" 
            }
        }

        stage ("stopFront") {
            steps {
				sh "sed -i 's+{{VERSION}}+${VERSION}+g' kubernates/front/frontDeployTemplate.yaml"
				sh "sed -i 's+{{REPO_NEXUS_URL}}+${REPO_NEXUS_URL}+g' kubernates/front/frontDeployTemplate.yaml"
				sh "sed -i 's+{{MY_LOGS}}+${MY_LOGS}+g' kubernates/front/frontDeployTemplate.yaml"
				sh "sed -i 's+{{ANGULAR_CONFIG}}+${ANGULAR_CONFIG}+g' kubernates/front/frontDeployTemplate.yaml"
				sh "cat kubernates/front/frontDeployTemplate.yaml"
                sh "kubectl apply -f kubernates/front/frontDeployTemplate.yaml" 
				
				sh "sed -i 's+{{SERVICE_EXTERNAL_IP}}+${SERVICE_EXTERNAL_IP}+g' kubernates/front/frontServiceTemplate.yaml"
				sh "cat kubernates/front/frontServiceTemplate.yaml"
                sh "kubectl apply -f kubernates/front/frontServiceTemplate.yaml" 
            }
        }
     }

     post { 
	always { 
		cleanWs()
	}
     }
}
