pipeline {
   agent { label 'stationslave' }
   
   tools { 
        maven 'Maven 3.3.9' 
        jdk 'jdk8' 
    }
   
    stages {
		
        stage ("startBack") {
            steps {
		sh "ls -lrt"
		sh "cat kubernates/back/backDeploy.yaml.template | sed 's/{{VERSION}}/${VERSION}}/g' > kubernates/back/backDeployTransform.yaml"
		sh "cat kubernates/back/backDeploy.yaml.template | sed 's/{{REPO_NEXUS_URL}}/${REPO_NEXUS_URL}}/g' > kubernates/back/backDeployTransform.yaml"
		sh "cat kubernates/back/backDeploy.yaml.template | sed 's/{{MY_LOGS}}/${MY_LOGS}}/g' > kubernates/back/backDeployTransform.yaml"
		sh "kubectl apply -f kubernates/back/backDeployTransform.yaml"
                sh "kubectl apply -f kubernates/back/backService.yaml" 
            }
        }

        stage ("stopFront") {
            steps {
		sh "cat kubernates/front/frontDeploy.yaml.template | sed 's/{{VERSION}}/${VERSION}}/g' > kubernates/front/frontDeployTransform.yaml"
		sh "cat kubernates/front/frontDeploy.yaml.template | sed 's/{{REPO_NEXUS_URL}}/${REPO_NEXUS_URL}}/g' > kubernates/front/frontDeployTransform.yaml"
		sh "cat kubernates/front/frontDeploy.yaml.template | sed 's/{{MY_LOGS}}/${MY_LOGS}}/g' > kubernates/front/frontDeployTransform.yaml"
		sh "cat kubernates/front/frontDeploy.yaml.template | sed 's/{{DATABASE_DATA}}/${DATABASE_DATA}}/g' > kubernates/front/frontDeployTransform.yaml"
                sh "kubectl apply -f kubernates/front/frontDeployTransform.yaml" 
                sh "kubectl apply -f kubernates/front/frontService.yaml" 
            }
        }
     }

     post { 
	always { 
		cleanWs()
	}
     }
}
