apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: station-aws-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: transverse
  project: shared
  source:
    chart: aws-load-balancer-controller
    helm:
      releaseName: aws-load-balancer-controller
      parameters: 
        - name: clusterName
          value: station-eks-cluster
        - name: serviceAccount.create
          value: "true" 
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: "arn:aws:iam::{{ .Values.app.accountidentifier }}:role/station-alb-iam-role" 
        - name: region
          value: {{ .Values.app.region | quote }}
        - name: vpcId
          value: {{ .Values.app.vpcId | quote }}
        - name: serviceAccount.name
          value: "station-aws-load-balancer-controller-sa"
        - name: image.repository
          value: "602401143452.dkr.ecr.eu-west-3.amazonaws.com/amazon/aws-load-balancer-controller"
        - name: nameOverride
          value: "station-aws-load-balancer-controller"
        - name: fullnameOverride
          value: "station-aws-load-balancer-controller"

    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.4.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true