apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: transverse
  project: shared
  source:
    chart: cert-manager
    helm:
      releaseName: cert-manager
      parameters: 
        - name: installCRDs
          value: "true"

    repoURL: https://charts.jetstack.io
    targetRevision: 1.9.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true