apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: station-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: transverse
  project: shared
  source:
    chart: kubernetes-external-secrets
    helm:
      releaseName: kubernetes-external-secrets
      parameters: 
        - name: serviceAccount.create
          value: "false"
        - name: env.AWS_REGION
          value: {{ .Values.app.region | quote }}
        - name: serviceAccount.name
          value: "station-external-secret-sa" 
        - name: fullnameOverride
          value: "station-external-secrets" 
        - name: fullnameOverride
          value: "station-external-secrets" 

    repoURL: https://external-secrets.github.io/kubernetes-external-secrets/
    targetRevision: 8.5.5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true