apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: station-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: transverse
  project: shared
  source:
    chart: external-secrets
    helm:
      releaseName: external-secrets
      parameters: 
        - name: serviceAccount.create
          value: "true"
        - name: serviceAccount.name
          value: "external-secrets-sa" 
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: "arn:aws:iam::{{ .Values.app.accountidentifier }}:role/station-secret-iam-role"
  
    repoURL: https://charts.external-secrets.io
    targetRevision: v0.5.9
  syncPolicy:
    automated:
      prune: true
      selfHeal: true