apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: station-metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: transverse
  project: default
  source:
    chart: metrics-server
    helm:
      releaseName: metrics-server
      parameters: 
        - name: serviceAccount.create
          value: "true"
        - name: serviceAccount.name
          value: "station-metrics-server-sa"
        - name: replicas
          value: "2" 

    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.8.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true