apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: shared
  source:
    chart: prometheus-operator-crds
    helm:
      releaseName: prometheus-operator-crds
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 5.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true