apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transverse
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: transverse
  project: shared
  source:
    chart: transverse
    helm:
      releaseName: transverse
      parameters: 
        - name: app.accountidentifier
          value: {{ .Values.app.accountidentifier | quote }}
        - name: app.region
          value: {{ .Values.app.region | quote }}
        - name: app.noderolearn
          value: {{ .Values.app.noderolearn | quote }}

    repoURL: {{ .Values.helm.repository | quote }} 
    targetRevision: 1.1.17
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true