version: '3.2'

services:
  station_db:
    image: mysql:latest
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure
    restart: always
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=StationDemoDb
      - MYSQL_USER=stationuser
      - MYSQL_PASSWORD=stationpwd
    volumes:
      - ./database_station/init:/docker-entrypoint-initdb.d
      - ./database_station/logs:/var/log/mysql
      - ./database_station/data:/var/lib/mysql
      - ./database_station/conf/test.cnf:/etc/mysql/mysql.conf.d/test.cnf
      
  station_back:
    depends_on:
      - station_db
    image: station_back:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - DB_TRAFSTAT_URL=jdbc:mysql://station_db:3306/StationDemoDb?connectTimeout=0
      - DB_TRAFSTAT_MAXACTIVE=100
      - DB_TRAFSTAT_USERNAME=stationuser  
      - DB_TRAFSTAT_PASSWORD=stationpwd   
    ports:
      - "4000:8080"
 
  station_front_tomcat:
    image: station_front_tomcat:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,address=10000,server=y,suspend=n"
    ports:
      - "4300:8080"
      - "10000:10000"

  station_front_nginx:
    image: nginx:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
        - "5000:80"
    volumes:
      - ./nginx_front/html:/usr/share/nginx/html:ro
      - ./nginx_front/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_front/logs:/var/log/nginx/
 
