# Value of station application
helm:
  repository: https://kagzouli.github.io/helm-charts/


image:
  repoNexusUrl:  


station:

  redis:
    mode: ""

    usessl: ""

  db:
    mode: ""

  back:
    ingressarn: ""

    albiplist: []

  front:
    ingressarn: ""

    albiplist: []