- name: "Preparation deploiement"
  hosts: allserver 
  roles:
   - role: "preparedeploy"

- name: "Deploiement backend"
  hosts: backend 
  roles:
   - role: "deploybackend"

- name: "Deploiement frontend"
  hosts: frontend 
  roles:
   - role: "deployfrontend"
