{{- if (eq .Values.stationdb.mode "externaldb")   }}
apiVersion: "kubernetes-client.io/v1" 
kind: ExternalSecret
metadata:
  name: stationdb-secret
  namespace:  {{ .Release.Namespace | quote }}
spec:
  backendType: secretsManager

  region: {{ .Values.app.network.region | quote  }} 

  data:
    

    - secretKey: database-rootpassword 
      remoteRef:
        key: stationsec-secretmanager
        property: stationdbrootpassword 
      

    - secretKey: database-password
      remoteRef:
        key: stationsec-secretmanager 
        property: stationdbpassword 


{{- end }}
