{{- if (eq .Values.secrets.mode "vault")   }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stationdb-secret
  namespace:  {{ .Release.Namespace | quote }}
spec:
  refreshInterval: "15s"

  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore

  data:
    

    - secretKey: database-rootpassword 
      remoteRef:
        key: /secrets/data/exaka/{{ .Values.app.environment}}/station
        property: stationdbrootpassword 
      

    - secretKey: database-password
      remoteRef:
        key: /secrets/data/exaka/{{ .Values.app.environment}}/station
        property: stationdbpassword 


{{- end }}
