apiVersion: apps/v1
kind: Deployment
metadata:
  name: stationfront-deploy
  namespace: {{ .Release.Namespace | quote }}
spec:
  # A deployment's specification really only 
  # has a few useful options
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  
  # 2. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      app:  stationfront
  
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: stationfront
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
      containers:
        - name: stationfront-nginx
          image: {{ include "stationfront.image.label" . | quote }} 
          imagePullPolicy: {{ .Values.stationfront.image.pullPolicy | quote }}
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
          env:
          - name: AWS_REGION
            value: {{ .Values.stationfront.region | quote  }}
          - name: CLIENT_ID_TRAF_STAT
            value: {{ .Values.stationfront.clientIdTrafStat | quote  }}
          - name: OKTA_URL
            value: {{ .Values.stationfront.oktaUrl | quote  }}
          - name: CONTEXT_BACK_URL
            value: {{ include "stationback.contextpath" . | quote }} 
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 200m
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /station-angular4-poc/index.html
              port: 8080
            initialDelaySeconds: 8
            periodSeconds: 5
            timeoutSeconds: 7
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /station-angular4-poc/index.html
              port: 8080
            initialDelaySeconds: 8
            periodSeconds: 5
            timeoutSeconds: 7
          ports:
          - containerPort: 8080
            protocol: TCP
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100  
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: stationfront
              topologyKey: kubernetes.io/hostname
