apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: stationfront-hpa
  namespace: {{ .Release.Namespace | quote }}
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stationfront-deploy
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # On mettrait plus une valeur de 60% dans la vraie vie.
        averageUtilization: 50