{{- if (eq .Values.app.hscaler "hpa")   }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stationback-hpa
  namespace: {{ .Release.Namespace | quote }}
spec:
  minReplicas: {{ .Values.stationback.nbReplicas }}
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: stationback-deploy
  metrics:
  - type: Pods
    pods:
      metric:
        name: http_server_requests_per_second
      target:
        type: AverageValue
        averageValue: 2
{{- end }}