{{- if (eq .Values.secrets.mode "vault")   }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace:  {{ .Release.Namespace | quote }}
spec:
  provider:
    vault:
      server: {{ .Values.secrets.vault.url | quote }}
      path: "secrets"
      version: {{ .Values.secrets.vault.version | quote }}
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-secret"
          namespace:  {{ .Release.Namespace | quote }}
          key: "token"
  
{{- end }}