{{- if (eq .Values.secrets.mode "aws")   }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stationdb-secret
  namespace:  {{ .Release.Namespace | quote }}
spec:

  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore

  data:
    

    - secretKey: database-rootpassword 
      remoteRef:
        key: stationsec-secretmanager
        property: stationdbrootpassword 
      

    - secretKey: database-password
      remoteRef:
        key: stationsec-secretmanager 
        property: stationdbpassword 


{{- end }}
