apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{station_namespace}}
spec:
  host: {{stationback.hostname}}
  path: /StationDemoSecureWeb 
  to:
    kind: Service
    name: stationbackservice
    weight: 100      # 100% traffic
  port:
    targetPort: stationback