apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stationback-hpa
  namespace: {{station_namespace}}
spec:
  minReplicas: {{stationback.nbReplicas}}
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stationback-deploy
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
