apiVersion: v1
kind: Service
metadata:
  name: stationredisservice 
  namespace: {{station_namespace}}
spec:
  type: ClusterIP
  ports:
  - port: 6379
    name: stationredis
    targetPort: 6379 
    protocol: TCP
  selector:
    app: stationredis
