- name: Message deploiement backend
  debug:
    msg: "Deploiement backend"

- name: Verifie si tomcat existe
  stat:
    path={{directory_work}}/tomcat9/bin
  register: existstomcat

- name: Telecharge tomcat
  get_url:
    url=http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.38/bin/apache-tomcat-9.0.38.tar.gz 
    dest="{{directory_tmp}}/apache-tomcat-9.0.38.tar.gz"
  when: not existstomcat.stat.exists

- name: Verifie existence repertoire tmp
  file:
    path: "{{directory_tmp}}"
    state: directory

- name: Verifie existence repertoire tomcat9
  file:
    path: "{{directory_work}}/tomcat9"
    state: directory

- name: extrait tomcat
  unarchive:
    src="{{directory_tmp}}/apache-tomcat-9.0.38.tar.gz"
    copy=no
    dest={{directory_tmp}} 
    creates=yes
  when: not existstomcat.stat.exists 

- name: copie Tomcat
  shell: cp -r {{directory_tmp}}/apache-tomcat-9.0.38/* {{directory_work}}/tomcat9 creates={{directory_work}}/tomcat9/bin
  when: not existstomcat.stat.exists

- name: Stop Tomcat
  command: "nohup {{directory_work}}/tomcat9/bin/shutdown.sh"

- name: Pause for 10 seconds for stop
  pause:
    seconds: 10

- name: Force la destruction de la tache
  shell: kill $(ps aux | grep 'tomcat9' | awk '{print $2}')
  ignore_errors: yes

- name: Detruit l'application ancienne
  file:
    path: "{{directory_work}}/tomcat9/webapps/StationDemoSecureWeb"
    state: absent

- name: Detruit le war StationDemoSecureWeb
  file:
    path: "{{directory_work}}/tomcat9/webapps/StationDemoSecureWeb.war"
    state: absent

- name: Copie WAR
  copy: src={{directory_saslivraison}}/StationDemoSecureWeb.war  dest={{directory_work}}/tomcat9/webapps/StationDemoSecureWeb.war  force=yes mode=776

- name: Start Tomcat
  command: "nohup {{directory_work}}/tomcat9/bin/startup.sh"
