apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: station
  namespace: stationdev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: station
    helm:
      releaseName: station
      parameters: 
        - name: stationback.ingress.targetGroupARN
          value: {{ .Values.station.back.ingressarn | quote }}
        - name: stationback.albiplist
          value: {{ .Values.station.back.albiplist | quote }}
        - name: stationfront.ingress.targetGroupARN
          value: {{ .Values.station.front.ingressarn | quote }}

    repoURL: {{ .Values.helm.repository | quote }} 
    targetRevision: 1.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true