apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: station
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: station
  project: default
  source:
    chart: station
    helm:
      releaseName: station
      parameters: 
        - name: stationback.ingress.targetGroupARN
          value: {{ .Values.station.back.ingressarn | quote }}
        - name: stationback.albiplist
          value: {{ .Values.station.back.albiplist | quote }}
        - name: stationfront.ingress.targetGroupARN
          value: {{ .Values.station.front.ingressarn | quote }}
        - name: stationfront.albiplist
          value: {{ .Values.station.front.albiplist | quote }}
        - name: stationredis.mode
          value: {{ .Values.station.redis.mode | quote }}
        - name: stationredis.usessl
          value: {{ .Values.station.redis.usessl | quote  }}
        - name: stationdb.mode
          value: {{ .Values.station.db.mode | quote }}
        - name: stationdb.storage.storageClass
          value: "none"
        - name: stationdb.storage.efsid
          value: ""
        - name: stationdb.storage.efsaccesspointid
          value: ""

    repoURL: {{ .Values.helm.repository | quote }} 
    targetRevision: 1.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true