name:  "[AWS] Build station Helm repo"

#on: [push]
on: 
  workflow_dispatch:
    inputs:

      helm_project_version:
        type: string
        default: 1.4.12
        description: station  project version
        required: true

env:
  STATION_HELM_REPO:  https://kagzouli.github.io/helm-charts/


jobs:

  # Deploy kubernetes station
  build_helm:
    runs-on: ubuntu-latest
    steps:

      # Retrieve a token for push
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}


      # Retrieve current source
      - name: Checkout current 
        id: checkout-current
        uses: actions/checkout@v3
        with:
          path: current
          token: ${{ steps.get_workflow_token.outputs.token }}

      # Retrieve helm repository
      - name: Checkout helm repo
        id: checkout-helm-repo
        uses: actions/checkout@v3
        with:
          repository: kagzouli/helm-charts
          path: helm-repo
          ref: main
          token: ${{ steps.get_workflow_token.outputs.token }}


      # Retrieve helm
      - name: Install Helm
        run: |
          curl -fsSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      # Copy aws value - Hack for AWS
      - name: Copy value station
        id: copy-value-station
        run: cp awsvalue.yaml station/values.yaml
        working-directory: current/kubernetesaws/helm


      # Generate package helm for station
      - name: package station
        id: package-station
        run: helm package station --version ${{ github.event.inputs.helm_project_version}}
        working-directory: current/kubernetesaws/helm

      # Copy station to helm repository
      - name: Copie station helm repo
        id: copy-station
        run: cp current/kubernetesaws/helm/station-${{ github.event.inputs.helm_project_version}}.tgz helm-repo/

      # Generate package helm for transverse
      - name: package transverse
        id: package-transverse
        run: helm package transverse --version ${{ github.event.inputs.helm_project_version}}
        working-directory: current/kubernetesaws/helm

      # Copy transverse to helm repository
      - name: Copie transverse helm repo
        id: copy-transverse
        run: cp current/kubernetesaws/helm/transverse-${{ github.event.inputs.helm_project_version}}.tgz helm-repo/

      # Index everything
      - name: index helm repo
        id: index-helm-repo
        run:  helm repo index helm-repo  --url ${{ env.STATION_HELM_REPO}} 


      # Push to Git repo
      - name: push index repo
        id: push-helm-repo
        run:  |
            git config --global user.name "kagzouli"
            git config --global user.email "noreply-kagzouli@exakaconsulting.org"
            git add . 
            git commit -m "Deploiement version ${{ github.event.inputs.helm_project_version}}" 
            git push origin main
        working-directory: helm-repo

