name:  "[Repo] Build custom image Runner"

#on: [push]
on: 
  workflow_dispatch:
    inputs:

      image_custom_version:
        type: string
        default: 1.1.1
        description: Image custom version.
        required: true

env:
  STATION_HELM_REPO:  https://kagzouli.github.io/helm-charts/