name: "[AWS] Build station on AWS"

#on: [pull_request]
on: 
  workflow_dispatch:
    inputs:

      environment:
        type: choice
        description: The environment to create
        options:
          - dev
        required: true

      docker_project_version:
        type: string
        default: 1.0.11
        description: station  project version
        required: true

      region:
        type: choice
        description: The region where we can create objects
        options:
          - eu-west-3
        required: true

env:
  NODEJS_VERSION: 14

jobs:

  # Deploy ECR
  ecr:
    uses: ./.github/workflows/terraform-ecr-reusable.yaml
    with:
      environment: ${{ github.event.inputs.environment}}
      region: ${{ github.event.inputs.region}}
    secrets:
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Push station front to dockerhub
  push_db_dockerhub:
    needs: ecr
    runs-on: ubuntu-latest
    steps:

      # Retrieve a token for pull
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}


      # Retrieve current source
      - name: Checkout current 
        id: checkout-current
        uses: actions/checkout@v3
        with:
          path: current
          token: ${{ steps.get_workflow_token.outputs.token }}

      # Get AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region}}
          role-duration-seconds: 3600

      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build db docker
      - name: Build db docker
        id: build-db-docker
        run: docker build -t ${{ steps.login-ecr.outputs.registry }}/station/station-db StationDemoDb
        working-directory: current/application

      # Tag db docker
      - name: Tag db docker
        id: tag-db-docker
        run: docker tag ${{ steps.login-ecr.outputs.registry }}/station/station-db:latest ${{ steps.login-ecr.outputs.registry }}/station/station-db:${{ github.event.inputs.docker_project_version}}

      # Push db docker
      - name: Push db docker
        id: push-db-docker
        run: docker push ${{ steps.login-ecr.outputs.registry }}/station/station-db:${{ github.event.inputs.docker_project_version}}
        
 
  build_backend:
    runs-on: ubuntu-latest
    needs: ecr
    steps:
      
      # Retrieve a token for pull
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}


      # Retrieve current source
      - name: Checkout current 
        id: checkout-current
        uses: actions/checkout@v3
        with:
          path: current
          token: ${{ steps.get_workflow_token.outputs.token }}

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build Backend
        id: build_backend
        run: mvn --batch-mode --update-snapshots package
        working-directory: current/application
 
      - name: Upload backend WAR
        id: upload-backendwar
        uses: actions/upload-artifact@v3
        with:
          name: backendwar
          path: current/application/spring-java/StationDemoWeb/target/StationDemoSecureWeb.war

  push_back_dockerhub:
    runs-on: ubuntu-latest
    needs: build_backend
    steps:

     # Retrieve a token for pull
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}


      # Retrieve current source
      - name: Checkout current 
        id: checkout-current
        uses: actions/checkout@v3
        with:
          path: current
          token: ${{ steps.get_workflow_token.outputs.token }}

      # Download artifact
      - name: download backend WAR
        id: download-backendwar
        uses: actions/download-artifact@v3
        with:
          name: backendwar
          path: current/application/spring-java/StationDemoWeb/docker/StationDemoSecureWeb.war
 
      # Get AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region}}
          role-duration-seconds: 3600

      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build back docker
      - name: Build Backenddocker
        id: build-backend-docker
        run: docker build -t ${{ steps.login-ecr.outputs.registry }}/station/station-back .
        working-directory: current/application/spring-java/StationDemoWeb/docker
 
      # Tag back docker
      - name: Tag Backenddocker
        id: tag-backend-docker
        run: docker tag ${{ steps.login-ecr.outputs.registry }}/station/station-back:latest ${{ steps.login-ecr.outputs.registry }}/station/station-back:${{ github.event.inputs.docker_project_version}}
 
      # Push back docker       
      - name: Push Backenddocker
        id: push-backend-docker
        run: docker push ${{ steps.login-ecr.outputs.registry }}/station/station-back:${{ steps.login-ecr.outputs.registry }}
 

            

  build_front:
    runs-on: ubuntu-latest
    needs: ecr
    steps:
      
      # Retrieve a token for pull
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}


      # Retrieve current source
      - name: Checkout current 
        id: checkout-current
        uses: actions/checkout@v3
        with:
          path: current
          token: ${{ steps.get_workflow_token.outputs.token }}

      # Install nodejs
      - name: Set up NodeJS ${{ env.NODEJS_VERSION}} 
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION}}
      - run: node --version
      
      # Build front
      - name: Install front Angular
        id: install-front-angular
        run: npm install
        working-directory: current/application/StationDemoClient/station-angular4-poc

      - name: Build front Angular
        id: build-front-angular
        run: npm run-script prod-zip
        working-directory: current/application/StationDemoClient/station-angular4-poc

      - name: Upload frontend zip
        id: upload-frontendangular
        uses: actions/upload-artifact@v3
        with:
          name: frontendangular
          path: current/application/StationDemoClient/station-angular4-poc/dist

        
  
  # Push station front to dockerhub
  push_front_dockerhub:
    runs-on: ubuntu-latest
    needs: build_front
    steps:

      # Retrieve a token for pull
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}


      # Retrieve current source
      - name: Checkout current 
        id: checkout-current
        uses: actions/checkout@v3
        with:
          path: current
          token: ${{ steps.get_workflow_token.outputs.token }}

      # Download artifact
      - name: download front end angular
        id: download-frontend-angular
        uses: actions/download-artifact@v3
        with:
          name: frontendangular
          path: current/application/StationDemoClient/station-angular4-poc/dockerwithnginx/dist


      # Get AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region}}
          role-duration-seconds: 3600

      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build front docker
      - name: Build frontendangular docker
        id: build-frontendangular-docker
        run: docker build -t ${{ steps.login-ecr.outputs.registry }}/station/station-front-nginx .
        working-directory: current/application/StationDemoClient/station-angular4-poc/dockerwithnginx
 
      # Tag front docker
      - name: Tag frontendangular docker
        id: tag-frontendangular-docker
        run: docker tag ${{ steps.login-ecr.outputs.registry }}/station/station-front-nginx:latest ${{ steps.login-ecr.outputs.registry }}/station/station-front-nginx:${{ github.event.inputs.docker_project_version}}
 
      # Push front docker      
      - name: Push frontendangular docker
        id: push-frontendangular-docker
        run: docker push ${{ steps.login-ecr.outputs.registry }}/station/station-front-nginx:${{ github.event.inputs.docker_project_version}}