name: Java CI

on: [pull_request]

env:
  NODEJS_VERSION: 14

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Set up NodeJS ${{ env.NODEJS_VERSION}} 
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION}}
      - run: node --version

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: application

      