name: "[Repo] Scan StationDemo"

#on: [pull_request]
on: 
  workflow_dispatch:
    inputs:

      docker_project_version:
        type: string
        default: 1.3.1
        description: station  project version
        required: true

env:
  NODEJS_VERSION: 14
  REPO_DOCKER_HUB: kagzouli3

jobs:


  scan_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability Back
        id: trivy_scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REPO_DOCKER_HUB }}/station-back:${{ github.event.inputs.docker_project_version}}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


  scan_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability Front
        id: trivy_scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REPO_DOCKER_HUB }}/station-front-nginx:${{ github.event.inputs.docker_project_version}}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'