name: "[Repo] Scan StationDemo"

#on: [pull_request]
on: 
  workflow_dispatch:
    inputs:

      docker_project_version:
        type: string
        default: 1.3.1
        description: station  project version
        required: true

env:
  NODEJS_VERSION: 14
  REPO_DOCKER_HUB: kagzouli3

jobs:


  scan_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability Back
        id: trivy_scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REPO_DOCKER_HUB }}/station-back:${{ github.event.inputs.docker_project_version}}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


  scan_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability Front
        id: trivy_scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REPO_DOCKER_HUB }}/station-front-nginx:${{ github.event.inputs.docker_project_version}}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  scan_helm:
    runs-on: ubuntu-latest
    steps:
      
      # Retrieve a token for pull
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}


      # Retrieve current source
      - name: Checkout current 
        id: checkout-current
        uses: actions/checkout@v3
        with:
          path: current
          token: ${{ steps.get_workflow_token.outputs.token }}

      - name: Get kubesec
        id: get-kube-sec
        run: |
          wget https://github.com/controlplaneio/kubesec/releases/download/v2.12.0/kubesec_linux_amd64.tar.gz
          tar -xvf kubesec_linux_amd64.tar.gz 
          mv kubesec ~/.local/bin/kubesec

      - name: Install Helm
        run: |
          curl -fsSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Scan template
        id: scan-helm-template
        run: helm template station > station.yaml && ~/.local/bin/kubesec station.yaml
        working-directory: current/kubernetesaws/helm
