name: "[AWS] Delete ECR"

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: The environment to create
        options:
          - dev
        required: true

      region:
        type: choice
        description: The region where we can create objects
        options:
          - eu-west-3
        required: true

env:
  TERRAFORM_VERSION: 0.15.5


jobs:

  # Delete ECR
  delete_ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        id: setup_terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION}} 
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region}}
          role-duration-seconds: 3600


      - name: ecr init
        id: init-ecr
        run: terraform init -backend-config="backends/${{ github.event.inputs.environment}}_backend.tfvars" 
        working-directory: terraformaws/ecr

      - name: ecr destroy
        id: destroy-ecr
        run: terraform destroy -auto-approve  --lock=false --var-file=../vars/${{ github.event.inputs.environment}}.tvars
        working-directory: terraformaws/ecr
