name: "[AWS] Delete all eks ArgoCD"

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: The environment to create
        options:
          - dev
        required: true

      region:
        type: choice
        description: The region where we can create objects
        options:
          - eu-west-3
        required: true

      supervision:
        type: choice
        description: Supervision (Oui/Non)
        default: non
        options:
          - non
          - oui
        required: true

      deployMode:
        type: choice
        description: Deploy mode (internal, external)
        default: internal
        options:
          - internal
          - external
        required: true


env:
  TERRAFORM_VERSION: 0.15.5


jobs:


  destroy_station:
    runs-on: ubuntu-latest
    # Il faut creer un environnement ou on specifie une validation (dev par example dans Settings) - Permet d'éviter de supprimer par erreur. 
    environment: ${{ github.event.inputs.environment}}
    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region}}
          role-duration-seconds: 3600

      - name: Install Helm
        run: |
          curl -fsSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: delete helm station
        id: delete-station
        run: |
          aws eks --region "eu-west-3" update-kubeconfig --name station-eks-cluster

          echo "Suppression du chart applications"
          helm delete applications

          echo "Delete transverse namespace and chart helm"
          helm delete shared

        working-directory: kubernetesaws/argocd

  delete_cloudwatchalarm:
    uses: ./.github/workflows/terraform-aws-destroy-reusable.yaml
    needs: destroy_station
    if: ${{ github.event.inputs.supervision == 'oui' }}
    with:
      environment: ${{ github.event.inputs.environment}}
      region: ${{ github.event.inputs.region}}
      component: cloudwatchalarm
    secrets:
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}  


  # Delete RDS
  delete_rds:
    uses: ./.github/workflows/terraform-aws-destroy-reusable.yaml
    if: ${{ github.event.inputs.deployMode == 'external' }}
    needs: destroy_station
    with:
      environment: ${{ github.event.inputs.environment}}
      region: ${{ github.event.inputs.region}}
      component: stationdb_rds
    secrets:
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

  # Delete Redis
  delete_redis:
    uses: ./.github/workflows/terraform-aws-destroy-reusable.yaml
    if: ${{ github.event.inputs.deployMode == 'external' }}
    needs: destroy_station
    with:
      environment: ${{ github.event.inputs.environment}}
      region: ${{ github.event.inputs.region}}
      component: stationredis
    secrets:
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

  #Delete EKS
  delete_eks:
    uses: ./.github/workflows/terraform-aws-destroy-reusable.yaml
    if: ${{ always() }}
    needs: [destroy_station , delete_rds]
    with:
      environment: ${{ github.event.inputs.environment}}
      region: ${{ github.event.inputs.region}}
      component: eks
    secrets:
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

 
  delete_secrets:
    uses: ./.github/workflows/terraform-aws-destroy-reusable.yaml
    needs: delete_eks
    if: ${{ always() }}
    with:
      environment: ${{ github.event.inputs.environment}}
      region: ${{ github.event.inputs.region}}
      component: secrets
    secrets:
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

  delete_networks:
    uses: ./.github/workflows/terraform-aws-destroy-reusable.yaml
    needs: delete_secrets
    with:
      environment: ${{ github.event.inputs.environment}}
      region: ${{ github.event.inputs.region}}
      component: networks
    secrets:
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
