name: Deploy EKS station

#on: [push]
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: The environment to create
        options:
          - dev
        required: true

#env:
#  ENVIRONMENT_NAME: dev

jobs:
  # Deploy networks
  networks:
    uses: ./.github/workflows/terraform-networks-reusable.yaml
    with:
      # environment: ${{ env.ENVIRONMENT_NAME}}
      environment: ${{ github.events.inputs.environment}}
    secrets:
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Deploy networks
  secrets:
    uses: ./.github/workflows/terraform-secrets-reusable.yaml
    needs: networks
    with:
      # environment: ${{ env.ENVIRONMENT_NAME}}
      environment: ${{ github.events.inputs.environment}}
    secrets:
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Deploy EKS
  eks:
    uses: ./.github/workflows/terraform-eks-reusable.yaml
    needs: secrets
    with:
      # environment: ${{ env.ENVIRONMENT_NAME}}
      environment: ${{ github.events.inputs.environment}}
    secrets:
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Deploy EKS
  deploystation:
    runs-on: ubuntu-latest
    needs: eks
    steps:
      - name: launch station
        id: launch-station
        run: launchAwsStationChart.sh internal
        working-directory: kubernetes
      