name: "[zzzzzz] Terraform rds"

on: 
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

      region:
        type: string
        required: true

    secrets:
      aws_access_key:
        required: true
      aws_secret_key:
        required: true

env:
  TERRAFORM_VERSION: 0.15.5

jobs:
  apply_rds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        id: setup_terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION}} 
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.aws_secret_key }}
          aws-region: ${{ github.event.inputs.region}}
          role-duration-seconds: 3600

      - name: rds init
        id: init-rds
        run: terraform init -backend-config="backends/${{ github.event.inputs.environment}}_backend.tfvars" 
        working-directory: terraformaws/stationdb_rds

      - name: rds plan
        id: plan-rds
        run: terraform plan  --lock=false --var-file=../vars/${{ github.event.inputs.environment}}.tvars
        working-directory: terraformaws/stationdb_rds

      - name: rds apply
        id: apply-rds
        run: terraform apply -auto-approve  --lock=false --var-file=../vars/${{ github.event.inputs.environment}}.tvars
        working-directory: terraformaws/stationdb_rds
      
