name: "[zzzzzz] Terraform component"

on: 
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

      region:
        type: string
        required: true

      component:
        type: string
        required: true

    secrets:
      aws_access_key:
        required: true
      aws_secret_key:
        required: true
      aws_role:
        required: true

env:
  TERRAFORM_VERSION: 1.1.7


jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        id: setup_terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION}} 
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.aws_secret_key }}
          role-to-assume: ${{ secrets.aws_role }}
          aws-region: ${{ inputs.region}}
          role-duration-seconds: 3600

      - name: Debug
        id: debug-karim
        run:  echo ${{ inputs.component}},${{ inputs.region}}

      - name: init
        id: init
        run: terraform init  -backend-config="backends/${{ inputs.environment}}_backend.tfvars"
        working-directory: terraformaws/${{ inputs.component}}

      - name: plan
        id: plan
        run: terraform plan  --lock=false --var-file=../vars/${{ inputs.environment}}.tvars
        working-directory: terraformaws/${{ inputs.component}}

      - name: apply
        id: apply
        run: terraform apply -auto-approve  --lock=false --var-file=../vars/${{ inputs.environment}}.tvars
        working-directory: terraformaws/${{ inputs.component}}
      
