name: Terraform network

on: 
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

    secrets:
      aws_access_key:
        required: true
      aws_secret_key:
        required: true

env:
  TERRAFORM_VERSION: 0.15.5
  ENVIRONMENT_NAME: dev

jobs:
  networks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        id: setup_terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION}} 
          terraform_wrapper: false

       - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.aws_secret_key }}
          role-duration-seconds: 3600

      - name: network init
        id: init-network-without-backend
        run: terraform init 
        working-directory: terraformaws/networks

      - name: network plan
        id: plan-network
        run: terraform plan  --lock=false --var-file=../vars/${{ github.event.inputs.environment}}.tvars
        working-directory: terraformaws/networks

      - name: network plan
        id: apply
        run: terraform apply -auto-approve  --lock=false --var-file=../vars/${{ github.event.inputs.environment}}.tvars
        working-directory: terraformaws/networks
      