name: "[AWS] Build docker station on AWS"

#on: [pull_request]
on: 
  push:
    paths:
      - terraformaws/eks/**

env:
  TERRAFORM_VERSION: 1.2.7
  NODEJS_VERSION: 14

jobs:
  validate_eks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        id: setup_terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION}} 
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_DEVOPS_CD }}
          aws-region: eu-west-3
          role-duration-seconds: 3600

      - name: init
        id: init
        run: terraform init  -backend-config="backends/dev_backend.tfvars"
        working-directory: terraformaws/eks


      - name: Validate terraform
        run:  terraform validate
        working-directory: terraformaws/eks


      - name: Download tfsec
        run:  curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash


      - name: Execute tfsec
        run: tfsec .
        working-directory: terraformaws/eks